### ISSUE TITLE
Feature: Editar dados do cliente

### ISSUE THREAD

**Issue by LMaroto** [LMaroto/SolarCalculator#4]
Criar uma nova página com formulário para editar informações do cliente.

**Comment by lhleonardo** [comment]
O problema é que isso poderá interferir em outros relatórios, já que isso irá resultar em um registro diferente na tabela de Goal. 

Isso vai interferir na aplicação? Os dados antigos devem ser mantidos?

**Comment by LMaroto** [comment]
A tabela de Goals está relacionada com a potência de usina do cliente (kWp). É interessante manter essa informação armazenada a fim de que se possa realizar análises mais detalhadas sobre a produção do mesmo.

**Comment by lhleonardo** [comment]
Só que ai complica.

Fica meio inviável manter um controle. Por exemplo: qual a melhor forma para os usuários que usam a plataforma para ter relatórios escolher um Goal específico para ser visualizado?

Qual a necessidade de ter armazenado um histórico de goals passados quando a potência da usina (armazenada como *kwp*) do cliente é modificada?

Descreve um pouco sobre a jornada que o usuário vai ter nesse processo e a necessidade dele quando um usuário tem seus dados alterados (destacando dados que vão modificar o relatório tal como a potência da usina e a produção estimada contratual)
