### ISSUE TITLE
Criação de nova coluna na tabela "Clientes"

### ISSUE THREAD

**Issue by LMaroto** [LMaroto/SolarCalculator#6]
Criar uma coluna com informações do modelo de inversor utilizado pelo cliente. Estes dados serão utilizados para a confecção do relatório individual de produção.

**Comment by lhleonardo** [comment]
@LMaroto Também deve ser relacionado a data que o inversor foi instalado? 

Lembro de um dos relatórios contabilizar a quantidade de dias que foram realizadas na análise.

**Comment by LMaroto** [comment]
@lhleonardo Não. A quantidade de dias mencionada diz respeito à data em que o inversor foi conectado à internet. Não é necessário armazenar essa data.

**Comment by lhleonardo** [comment]
No fim das contas relacionei o inversor com uma data de instalação para customizar intervalos de tempo no relatório.

Foi resolvido no commit #b2b8bc7
