### ISSUE TITLE
Código do cliente

### ISSUE THREAD

**Issue by LMaroto** [LMaroto/SolarCalculator#7]
Alterar a forma de armazenamento do código do cliente. Atualmente, estamos armazenando através da chave primária no banco de dados. O ideal seria inserir essa informação manualmente, haja vista que existem clientes com mais de uma usina fotovoltaica, o que pode causar confusão com as informações armazenadas pela empresa. Por exemplo, se o cliente 1 possuir mais de uma usina, a empresa as identificará como 1 - A e 1 - B, o que não é possível na forma como estamos armazenando as informações.

**Comment by lhleonardo** [comment]
OK.

Por questões de melhor estrutura e armazenamento, o código que referencia um item no banco de dados será armazenado utilizando número auto incrementável, da mesma forma que está sendo feito atualmente.

Será adicionada uma coluna no banco de dados chamada **Número da ficha** que terá preenchimento obrigatório e o usuário será capaz de informar o seu valor. 

Esse campo será utilizando apenas na visualização das informações, mas sempre será referenciado a partir do código auto incrementável pelas funções presentes no sistema.

Em breve relaciono um commit para finalizar essa issue.

**Comment by lhleonardo** [comment]
Implementação concluída a partir de um código obrigatório enviado no momento do cadastro.
