### ISSUE TITLE
Dashboard para escolha de operações

### ISSUE THREAD

**Issue by lhleonardo** [LMaroto/SolarCalculator#9]
No intuito de facilitar na utilização é requisitada a criação de uma página inicial que ofereça suporte para:

1. Gerenciar os clientes (listagem, cadastro, lançamento de leitura, etc);
2. Emitir relatório de consumo geral (mensal, intervalado, etc);
3. Configurar os parâmetros do sistema: cidades e seus respectivos valores solares para cálculos

Uma possível implementação pode ser ilustrada com a imagem abaixo: 

![Captura de tela 2020-09-25 140125](https://user-images.githubusercontent.com/11544276/94300924-b00abf80-ff37-11ea-8f42-6d14b2b55b9d.png)

**Comment by LMaroto** [comment]
Fiz um pouco diferente da ideia inicial.
![image](https://user-images.githubusercontent.com/59891332/94355964-09b5db80-0057-11eb-9f0f-8a42bca0bb52.png)
Vou deixar a issue aberta até ajeitar a cor da logo para que fique adequada à página.
